/**
 * @fileoverview gRPC-Web generated client stub for chat
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.0
// source: chat.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from "grpc-web";
import * as chatPbRaw from "@local/chat-protos";
const chat_pb: any = (chatPbRaw as any).default ?? chatPbRaw;


export class ChatClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorOpenOrGetConversation = new grpcWeb.MethodDescriptor(
    '/chat.Chat/OpenOrGetConversation',
    grpcWeb.MethodType.UNARY,
    chat_pb.OpenOrGetConversationRequest,
    chat_pb.OpenOrGetConversationResponse,
    (request: chat_pb.OpenOrGetConversationRequest) => {
      return request.serializeBinary();
    },
    chat_pb.OpenOrGetConversationResponse.deserializeBinary
  );

  openOrGetConversation(
    request: chat_pb.OpenOrGetConversationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<chat_pb.OpenOrGetConversationResponse>;

  openOrGetConversation(
    request: chat_pb.OpenOrGetConversationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chat_pb.OpenOrGetConversationResponse) => void): grpcWeb.ClientReadableStream<chat_pb.OpenOrGetConversationResponse>;

  openOrGetConversation(
    request: chat_pb.OpenOrGetConversationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chat_pb.OpenOrGetConversationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chat.Chat/OpenOrGetConversation',
        request,
        metadata || {},
        this.methodDescriptorOpenOrGetConversation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chat.Chat/OpenOrGetConversation',
    request,
    metadata || {},
    this.methodDescriptorOpenOrGetConversation);
  }

  methodDescriptorSendMessage = new grpcWeb.MethodDescriptor(
    '/chat.Chat/SendMessage',
    grpcWeb.MethodType.UNARY,
    chat_pb.SendMessageRequest,
    chat_pb.SendMessageResponse,
    (request: chat_pb.SendMessageRequest) => {
      return request.serializeBinary();
    },
    chat_pb.SendMessageResponse.deserializeBinary
  );

  sendMessage(
    request: chat_pb.SendMessageRequest,
    metadata?: grpcWeb.Metadata | null): Promise<chat_pb.SendMessageResponse>;

  sendMessage(
    request: chat_pb.SendMessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chat_pb.SendMessageResponse) => void): grpcWeb.ClientReadableStream<chat_pb.SendMessageResponse>;

  sendMessage(
    request: chat_pb.SendMessageRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chat_pb.SendMessageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chat.Chat/SendMessage',
        request,
        metadata || {},
        this.methodDescriptorSendMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chat.Chat/SendMessage',
    request,
    metadata || {},
    this.methodDescriptorSendMessage);
  }

  methodDescriptorListMessages = new grpcWeb.MethodDescriptor(
    '/chat.Chat/ListMessages',
    grpcWeb.MethodType.UNARY,
    chat_pb.ListMessagesRequest,
    chat_pb.ListMessagesResponse,
    (request: chat_pb.ListMessagesRequest) => {
      return request.serializeBinary();
    },
    chat_pb.ListMessagesResponse.deserializeBinary
  );

  listMessages(
    request: chat_pb.ListMessagesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<chat_pb.ListMessagesResponse>;

  listMessages(
    request: chat_pb.ListMessagesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chat_pb.ListMessagesResponse) => void): grpcWeb.ClientReadableStream<chat_pb.ListMessagesResponse>;

  listMessages(
    request: chat_pb.ListMessagesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chat_pb.ListMessagesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chat.Chat/ListMessages',
        request,
        metadata || {},
        this.methodDescriptorListMessages,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chat.Chat/ListMessages',
    request,
    metadata || {},
    this.methodDescriptorListMessages);
  }

  methodDescriptorSubscribeMessages = new grpcWeb.MethodDescriptor(
    '/chat.Chat/SubscribeMessages',
    grpcWeb.MethodType.SERVER_STREAMING,
    chat_pb.SubscribeMessagesRequest,
    chat_pb.Message,
    (request: chat_pb.SubscribeMessagesRequest) => {
      return request.serializeBinary();
    },
    chat_pb.Message.deserializeBinary
  );

  subscribeMessages(
    request: chat_pb.SubscribeMessagesRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<chat_pb.Message> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chat.Chat/SubscribeMessages',
      request,
      metadata || {},
      this.methodDescriptorSubscribeMessages);
  }

}

