/**
 * @fileoverview gRPC-Web generated client stub for chat
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.33.4
// source: chat.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.chat = require('./chat_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.chat.ChatClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.chat.ChatPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.OpenOrGetConversationRequest,
 *   !proto.chat.OpenOrGetConversationResponse>}
 */
const methodDescriptor_Chat_OpenOrGetConversation = new grpc.web.MethodDescriptor(
  '/chat.Chat/OpenOrGetConversation',
  grpc.web.MethodType.UNARY,
  proto.chat.OpenOrGetConversationRequest,
  proto.chat.OpenOrGetConversationResponse,
  /**
   * @param {!proto.chat.OpenOrGetConversationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.OpenOrGetConversationResponse.deserializeBinary
);


/**
 * @param {!proto.chat.OpenOrGetConversationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chat.OpenOrGetConversationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chat.OpenOrGetConversationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chat.ChatClient.prototype.openOrGetConversation =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chat.Chat/OpenOrGetConversation',
      request,
      metadata || {},
      methodDescriptor_Chat_OpenOrGetConversation,
      callback);
};


/**
 * @param {!proto.chat.OpenOrGetConversationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chat.OpenOrGetConversationResponse>}
 *     Promise that resolves to the response
 */
proto.chat.ChatPromiseClient.prototype.openOrGetConversation =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chat.Chat/OpenOrGetConversation',
      request,
      metadata || {},
      methodDescriptor_Chat_OpenOrGetConversation);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.SendMessageRequest,
 *   !proto.chat.SendMessageResponse>}
 */
const methodDescriptor_Chat_SendMessage = new grpc.web.MethodDescriptor(
  '/chat.Chat/SendMessage',
  grpc.web.MethodType.UNARY,
  proto.chat.SendMessageRequest,
  proto.chat.SendMessageResponse,
  /**
   * @param {!proto.chat.SendMessageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.SendMessageResponse.deserializeBinary
);


/**
 * @param {!proto.chat.SendMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chat.SendMessageResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chat.SendMessageResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chat.ChatClient.prototype.sendMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chat.Chat/SendMessage',
      request,
      metadata || {},
      methodDescriptor_Chat_SendMessage,
      callback);
};


/**
 * @param {!proto.chat.SendMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chat.SendMessageResponse>}
 *     Promise that resolves to the response
 */
proto.chat.ChatPromiseClient.prototype.sendMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chat.Chat/SendMessage',
      request,
      metadata || {},
      methodDescriptor_Chat_SendMessage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.ListMessagesRequest,
 *   !proto.chat.ListMessagesResponse>}
 */
const methodDescriptor_Chat_ListMessages = new grpc.web.MethodDescriptor(
  '/chat.Chat/ListMessages',
  grpc.web.MethodType.UNARY,
  proto.chat.ListMessagesRequest,
  proto.chat.ListMessagesResponse,
  /**
   * @param {!proto.chat.ListMessagesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.ListMessagesResponse.deserializeBinary
);


/**
 * @param {!proto.chat.ListMessagesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chat.ListMessagesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chat.ListMessagesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chat.ChatClient.prototype.listMessages =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chat.Chat/ListMessages',
      request,
      metadata || {},
      methodDescriptor_Chat_ListMessages,
      callback);
};


/**
 * @param {!proto.chat.ListMessagesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chat.ListMessagesResponse>}
 *     Promise that resolves to the response
 */
proto.chat.ChatPromiseClient.prototype.listMessages =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chat.Chat/ListMessages',
      request,
      metadata || {},
      methodDescriptor_Chat_ListMessages);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.SubscribeMessagesRequest,
 *   !proto.chat.Message>}
 */
const methodDescriptor_Chat_SubscribeMessages = new grpc.web.MethodDescriptor(
  '/chat.Chat/SubscribeMessages',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.chat.SubscribeMessagesRequest,
  proto.chat.Message,
  /**
   * @param {!proto.chat.SubscribeMessagesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.Message.deserializeBinary
);


/**
 * @param {!proto.chat.SubscribeMessagesRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.chat.Message>}
 *     The XHR Node Readable Stream
 */
proto.chat.ChatClient.prototype.subscribeMessages =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/chat.Chat/SubscribeMessages',
      request,
      metadata || {},
      methodDescriptor_Chat_SubscribeMessages);
};


/**
 * @param {!proto.chat.SubscribeMessagesRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.chat.Message>}
 *     The XHR Node Readable Stream
 */
proto.chat.ChatPromiseClient.prototype.subscribeMessages =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/chat.Chat/SubscribeMessages',
      request,
      metadata || {},
      methodDescriptor_Chat_SubscribeMessages);
};


module.exports = proto.chat;

